blog/urls.py
from django.urls import path
from blog.views import all_post_view,category_view,tag_view,post_detail

app_name='blog'
urlpatterns = [
    #all post
    path('', all_post_view, name='all_post_view'),
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),
    #post detail
    path('category/<slug:category_slug>/<slug:post_slug>/', post_detail, name='post_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#MY APPS
from config.views import logout_view
from page.views import home_view


urlpatterns = [
    path('', home_view, name='home'),
    

    #page
    path('page/', include('page.urls', namespace='page')),

    
    # Blog App:
    path('blog/', include('blog.urls', namespace='blog')),

    #todo app
    path('todo/', include('todo.urls', namespace='todo')),

    #tinymce
    path('tinymce/', include('tinymce.urls')),

    #auth
    path('account/logout', logout_view, name='logout_view'),

    #admin
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DjangoMania</title>
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include 'core/navbar.html' %}

    {% block container-fluid %}
    {% endblock %}

    <div class="container my-5">

        {% block container %}
        {% endblock container %}

    </div>
    
    {% include 'core/footer.html' %}
    <!-- JS -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

templates/core/footer.html
<div class="bg-dark py-5 mt-5">
    <div class="container">
        <div class="col">
            <h1 class="text-light">DjangoMania</h1>
        </div>
    </div>
</div>

templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">DjangoMania</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Anasayfa</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Todo Kategoriler
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in global_todo_categories %}
                        <li><a class="dropdown-item" href="{{ category.get_absolute_urls }}">{{ category.title }}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </li>

                {% for page in global_pages %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ page.get_absolute_urls }}">{{ page.title }}</a>
                </li>
                {% endfor %}

                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'blog:all_post_view' %}">Blog</a>
                </li>

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'logout_view' %}">Oturumu Kapat</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>